required = ["github.com/labstack/echo"]

[[constraint]]
name =  "github.com/labstack/echo"
version = "3.2.1"

[[constraint]]
name =  "github.com/go-sql-driver/mysql"
version = "1.3"

[[constraint]]
name =  "upper.io/db.v3"
version = "3.3.0"